### ISSUE TITLE
[Resolved][Partially fixed] Null, encoding, language

### ISSUE THREAD

**Issue by bartoszsledz** [inzOprogramowaniaUZ/violetumleditor#49]
1. NUll when project is not saved (should be e.g. Unsaved class diagram).
2. Encoding in welcome frame, interface and enumeration nodes.
3. Welcome frame doesn't include the current language (Always in polish).

![123](https://cloud.githubusercontent.com/assets/18503019/23070076/271901e8-f52a-11e6-8716-2eb3b1ff3ae2.png)
![null](https://cloud.githubusercontent.com/assets/18503019/23070075/2718388a-f52a-11e6-95f1-d0a4d0a97a35.png)

**Comment by RoughTomato** [comment]
apparently the default font does not correspond well with UTF-8 glyphs. I'll try to fix that.

**Comment by RoughTomato** [comment]
I've fixed encoding problems as it directly correspond to previous problems we had in that matter. @lormniczek hard coded welcome frame JButton messages without regard for currently selected language and should be in separate issue assigned to @lormniczek. As for "null class diagram" instead of "unsaved class diagram" I'll check it out.

**Comment by abizukojc** [comment]
```
  1. NUll when project is not saved (should be e.g. Unsaved class diagram).
  2. Encoding in welcome frame, interface and enumeration nodes.
  3. Welcome frame doesn't include the current language (Always in polish).
```
It's too many things for one bug issue.

**Comment by bartoszsledz** [comment]
Resolved.
